name: wanandroid_flutter
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_swiper: ^1.1.6
  dio: ^2.1.0
  json_annotation: ^2.0.0
  flutter_webview_plugin: ^0.3.3
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.3
  event_bus: ^1.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.1.2
  json_serializable: ^2.0.1


flutter:

  uses-material-design: true


